logging:
  level: INFO
  loggers:
    com.javaperks.api: DEBUG
server:
  applicationConnectors:
  - type: http
    bindHost: 0.0.0.0
    port: 5822
  adminConnectors:
  - type: http
    bindHost: 0.0.0.0
    port: 9001
