version: 2
jobs:
  build:
    working_directory: ~/javaperks-customer-api
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli
      - restore_cache:
          key: javaperks-customer-api-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: javaperks-customer-api-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/javaperks-customer-api-0.1.0-SNAPSHOT.jar
      - deploy:
          name: Upload to S3
          command: |
            aws s3 cp target/javaperks-customer-api-0.1.0-SNAPSHOT.jar s3://jubican-public/jars/javaperks-customer-api-0.1.0-SNAPSHOT.jar --region=us-west-2

